### ISSUE TITLE
Add test mode for verb pages

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/discipulis#34]

**Comment by sonicx180** [comment]
lmao, can these become bounties for me ? I would be very happy if they did :)

**Comment by VulcanWM** [comment]
> lmao, can these become bounties for me ? I would be very happy if they did :)

As much as I love letting others do my work and paying them, I need to acc work on my next.js skills
Also I’ve worked on the noun version of this, just need to implement it to the verb page
Have fun with the flip animation bounty though

**Comment by sonicx180** [comment]
I agree. I wish I learned nextjs like you did :) Also, thanks for accepting me!
